export const ActionType = {

    /**
     * Users Actions
     */
    IS_AUTHENTICATE: 'IS_AUTHENTICATE',
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    USER_DETAILS: "USER_DETAILS",
    SETTINGS: "SETTINGS",
    USER_REGISTRATION: "USER_REGISTRATION",
    USER_REGISTRATION_ROLE: "USER_REGISTRATION_ROLE",
    VERIFY_EMAIL: "VERIFY_EMAIL",
    EMPLOYEE_DETAILS: "EMPLOYEE_DETAILS",
    SKILLS: "SKILLS",
    EMPLOYER_DETAILS: "EMPLOYER_DETAILS",
    USER_LIST: "USER_LIST",
    NOTIFICATION_LIST: "NOTIFICATION_LIST",
    ACKNOWLEDMENT: "ACKNOWLEDMENT",
    TIME_LEFT: "TIME_LEFT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    SUB_USER: "SUB_USER",
    SUB_USER_LIST: "SUB_USER_LIST",
    /**
     * Messages
     */

    ROOM_LIST: 'ROOM_LIST',
    ROOM_DETAILS: 'ROOM_DETAILS',
    TOTAL_UNREADCOUT: "TOTAL_UNREADCOUT",
    ROOM_ID: "ROOM_ID",

    /**
     * Plan
     */

    PLAN_LIST: "PLAN_LIST",
    JOB_SLOTS_PLAN_LIST: "JOB_SLOTS_PLAN_LIST",
    SLOT_PLANS: "SLOT_PLANS",
    SUBSCRIPTION_LIST: "SUBSCRIPTION_LIST",
    SUBSCRIPTION_INFO: "SUBSCRIPTION_INFO",

    /**
     * Job Posting
     */

    JOB_DETAILS: "JOB_DETAILS",
    DESIGNATION_LIST: "DESIGNATION_LIST",
    JOBTYPE_LIST: "JOBTYPE_LIST",
    SAVED_JOB_LISTING: "SAVED_JOB_LISTING",
    HIRING_TIMELINE_LIST: "HIRING_TIMELINE_LIST",
    ROLE_LIST: "ROLE_LIST",

    /**
     * Employee Dashboard
     */

    PREFRENCE_JOBS: "PREFRENCE_JOBS",
    JOB_DETAILS: "JOB_DETAILS",
    FILTER_JOB: "FILTER_JOB",
    TRACKED_JOB: "TRACKED_JOB",

    /**
     * Employer Dashboard
     */

    FILTER_CANDIDATE: "FILTER_CANDIDATE",
    JOB_POSTED: "JOB_POSTED",
    APPLICANT_LIST: "APPLICANT_LIST",
    HIRED_CANDIDATE_LIST: "HIRED_CANDIDATE_LIST",
    SAVED_TALENT_LIST: "SAVED_TALENT_LIST",
    APPLIED_CANDIDATE: "APPLIED_CANDIDATE",
    SERVICE_LIST: "SERVICE_LIST",
    JOB_NAMES: "JOB_NAMES",

    /**
     * Comman
     */

    ALL_USER_DETAILS: "ALL_USER_DETAILS",
    CATEGORIES_LIST: "CATEGORIES_LIST",
    UPDATE_EMPLOYER_ID: "UPDATE_EMPLOYER_ID",
    JOB_TYPE: "JOB_TYPE",
    JOB_TYPE_COUNT: "JOB_TYPE_COUNT",
    NOTIFICATIONS_LIST: 'NOTIFICATIONS_LIST',
    COMMENT_LIST: "COMMENT_LIST",
    PUBLIC_PROFILE: "PUBLIC_PROFILE",

    /**
     * CMS
     */
    CONTENT_DATA: "CONTENT_DATA",


    /**
     * Meeting
     */
    MEETING_EVENTS: "MEETING_EVENTS",
    MEETING_EVENTS_LIST: "MEETING_EVENTS_LIST",
    MEETING_EVENTS_BY_DATE: "MEETING_EVENTS_BY_DATE",
    MEETING_UPCOMING_PAST: "MEETING_UPCOMING_PAST",

    /**
     FEEDBACK
     */
    SUBMIT_FEEDBACK: "SUBMIT_FEEDBACK",
    SUBMIT_WEBSITE_FEEDBACK: "SUBMIT_WEBSITE_FEEDBACK",

};